name: Python FastAPI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    - name: Run tests with coverage
      env:
        APP_NAME: LDAP-FastAPI
        LOG_LEVEL: INFO
        DATABASE_URL: sqlite:///./test.db
        QUEUE_URL: redis://localhost:6379/0
        LDAP_URL: ldap://localhost:389
        LDAP_BIND_DN: cn=admin,dc=example,dc=com
        LDAP_BIND_PASSWORD: admin
        SECRET_KEY: supersecretkey
      run: |
        export PYTHONPATH=$PWD
        coverage run -m pytest tests/ --maxfail=1 --disable-warnings -v
        coverage report -m
        coverage xml
